name: CI Pipeline

on: [push, pull_request]  # Triggers on pushes and PRs

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
              
          
      - name: Verify HTML form exists
        run: |
          ls | grep register.html
          echo "Form validation complete"
